---

###
### Enable sudo (required for docker service)
###
sudo: required


###
### Language
###
language: minimal


###
### Lint
###
before_script:
  - make lint


###
### Test
###
script:
  - make test
